version: '2'
services:
  db:
    image: mysql/mysql-server:5.5
    volumes:
      - ~/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=tacrm_production
      - MYSQL_USER=tacrm_admin
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    expose:
      - "3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.6.4-1
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions
    links:
     - db
  tacrm:
    image: jchan917/tacrm:latest
    container_name: tacrm_dev
    volumes:
      - ~/uploads/development:/development
    environment:
     - MYSQL_URL=db
     - RAILS_ENV=development
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db
    links:
      - db
    ports:
      - "3000:3000"
    entrypoint: ./wait-for-it.sh db:3306 -t 30 --strict -- ./start.sh