module LocationHelper
  def ph_airports_list
    [
     ["Manila","MNL"],
     ["Clark","CRK"],
     ["Bacolod-Silay","BCD"],
     ["Davao","DVO"],
     ["General Santos","GES"],
     ["Iloilo","ILO"],
     ["Kalibo","KLO"],
     ["Laoag","LAO"],
     ["Cebu","CEB"],
     ["Puerto Princesa","PPS"],
     ["Subic Bay","SFS"],
     ["Zamboanga","ZAM"],
     ["Bancasi/Butuan","BXU"],
     ["Awang/Cotabato","CBO"],
     ["Dipolog","DPL"],
     ["Sibulan/Dumaguete","DGT"],
     ["Laguindingan","CGY"],
     ["Legazpi","LGP"],
     ["Naga/Pili","WNP"],
     ["Pagadian","PAG"],
     ["Roxas","RXS"],
     ["San Jose","SJI"],
     ["Daniel Z. Romualdez/Tacloban","TAC"],
     ["Tagbilaran","TAG"],
     ["Tuguegarao","TUG"],
     ["Evelio Javier/Antique","EUQ"],
     ["Loakan/Baguio","BAG"],
     ["Basco","BSO"],
     ["Sanga-Sanga/Tawi-Tawi","SGS"],
     ["Francisco B. Reyes/Busuanga-Coron","USU"],
     ["Calbayog","CYP"],
     ["Camiguin","CGM"],
     ["Catarman National","CRM"],
     ["Godofredo P. Ramos/Caticlan","MPH"],
     ["Cuyo","CYU"],
     ["Jolo","JOL"],
     ["Marinduque","MRQ"],
     ["Moises R. Espinosa/Masbate","MBT"],
     ["Ormoc","OMC"],
     ["Tugdan/Romblon","TBH"],
     ["Sayak/Siargao","IAO"],
     ["Surigao","SUG"],
     ["Tandag","TDG"],
     ["Virac","VRC"],
     ["Alabat","Alabat"],
     ["Allah Valley","AAV"],
     ["Bagabag","Bagabag"],
     ["Dr. Juan C. Angara/Baler","BQA"],
     ["Bantayan","Bantayan"],
     ["Biliran","Biliran"],
     ["Bislig","BPH"],
     ["Borongan/Punta Maria","BPR"],
     ["Bulan","Bulan"],
     ["Calapan","CPP"],
     ["Cagayan de Sulu/Mapun","CDY"],
     ["Catbalogan","Catbalogan"],
     ["Cauayan","CYZ"],
     ["Bagasbas/Daet","DTE"],
     ["Guiuan","Guiuan"],
     ["Hilongos","Hilongos"],
     ["Iba","Iba"],
     ["Maria Cristina/Iligan","IGN"],
     ["Ipil","IPE"],
     ["Itbayat","Itbayat"],
     ["Jomalig","Jomalig"],
     ["Liloy","Liloy"],
     ["Lingayen","Lingayen"],
     ["Lubang","LBX"],
     ["Panan-awan/Maasin","Maasin"],
     ["Malabang","MLP"],
     ["Mamburao","MBO"],
     ["Wasig/Mansalay","Mansalay"],
     ["Mati /formerly Imelda R. Marcos","MXI"],
     ["Labo/Ozamiz","OZC"],
     ["Palanan","Palanan"],
     ["Pinamalayan","Pinamalayan"],
     ["Plaridel","Plaridel"],
     ["Rosales","Rosales"],
     ["San Fernando/Poro Point","SFE"],
     ["Siocon","XSO"],
     ["Siquijor","Siquijor"],
     ["Sorsogon/Gabao/Bacon","Sorsogon"],
     ["Ubay","Ubay"],
     ["Mindoro/Vigan","VGN"],
     ["Wao", "WAO"]
    ]
  end
end